name: PortfolioF
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  lottie: ^3.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
